// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestCompare_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewCompare()

	called := false
	cmd.CommandAction = func(c *Compare) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "test")
	args = append(args, "test")
	args = append(args, "--term")
	args = append(args, "--interactive")
	args = append(args, "--maxLines")
	args = append(args, "1")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.file1 != "test" {
		t.Errorf("Expected file1 to be 'test', got '%v'", cmd.file1)
	}
	if cmd.file2 != "test" {
		t.Errorf("Expected file2 to be 'test', got '%v'", cmd.file2)
	}
	if cmd.term != true {
		t.Errorf("Expected term to be true, got '%v'", cmd.term)
	}
	if cmd.interactive != true {
		t.Errorf("Expected interactive to be true, got '%v'", cmd.interactive)
	}
	if cmd.maxLines != 1 {
		t.Errorf("Expected maxLines to be 1, got '%v'", cmd.maxLines)
	}
}
