// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	app "github.com/arran4/golang-diff"
)

var _ Cmd = (*Compare)(nil)

type Compare struct {
	*RootCmd
	Flags          *flag.FlagSet
	file1          string
	file2          string
	term           bool
	interactive    bool
	searchDepth    int
	limitLines     int
	limitWidth     int
	linesSelection string
	widthSelection string
	SubCommands    map[string]func() Cmd
	CommandAction  func(c *Compare) error
}

type UsageDataCompare struct {
	*Compare
	Recursive bool
}

func (c *Compare) Usage() {
	err := executeUsage(os.Stderr, "compare_usage.txt", UsageDataCompare{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Compare) UsageRecursive() {
	err := executeUsage(os.Stderr, "compare_usage.txt", UsageDataCompare{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Compare) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "term":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.term = b
				} else {
					c.term = true
				}

			case "interactive":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.interactive = b
				} else {
					c.interactive = true
				}

			case "searchDepth", "search-depth":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.searchDepth = v

			case "limitLines", "max-lines":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.limitLines = v

			case "limitWidth", "max-width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.limitWidth = v

			case "linesSelection", "lines":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.linesSelection = value

			case "widthSelection", "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.widthSelection = value
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "t" {
					found = true
					c.term = true
				}

				if char == "i" {
					found = true
					c.interactive = true
				}

				if char == "s" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					v, err := strconv.Atoi(value)
					if err != nil {
						return fmt.Errorf("invalid integer value for flag -%s: %s", char, value)
					}
					c.searchDepth = v
				}

				if char == "l" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.linesSelection = value
				}

				if char == "w" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.widthSelection = value
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 2 {
		return fmt.Errorf("expected at least 2 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument file1
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.file1 = argVal
		}
	}
	// Handle positional argument file2
	{
		argIndex := 1
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.file2 = argVal
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("compare failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewCompare() *Compare {
	set := flag.NewFlagSet("compare", flag.ContinueOnError)
	v := &Compare{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.term, "term", false, "Terminal mode (colors)")
	set.BoolVar(&v.term, "t", false, "Terminal mode (colors)")

	set.BoolVar(&v.interactive, "interactive", false, "Interactive mode")
	set.BoolVar(&v.interactive, "i", false, "Interactive mode")

	set.IntVar(&v.searchDepth, "search-depth", 1000, "Max lines to search for alignment")
	set.IntVar(&v.searchDepth, "s", 1000, "Max lines to search for alignment")

	set.IntVar(&v.limitLines, "max-lines", 0, "Max lines to compare")

	set.IntVar(&v.limitWidth, "max-width", 0, "Max width")

	set.StringVar(&v.linesSelection, "lines", "", "Line selection")
	set.StringVar(&v.linesSelection, "l", "", "Line selection")

	set.StringVar(&v.widthSelection, "width", "", "Width selection")
	set.StringVar(&v.widthSelection, "w", "", "Width selection")
	set.Usage = v.Usage

	v.CommandAction = func(c *Compare) error {

		app.CompareFiles(c.file1, c.file2, c.term, c.interactive, c.searchDepth, c.limitLines, c.limitWidth, c.linesSelection, c.widthSelection)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
