version: 2
project_name: golang-diff
builds:
  - id: diff
    binary: diff
    main: ./cmd/diff
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: arran4
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        base:
          owner: arran4
          name: homebrew-tap
          branch: main
